"""cambio de nombre modelo Disponibilidad a Hora

Revision ID: 7a453d2c4da9
Revises: becc8104e8c9
Create Date: 2025-01-11 13:54:05.079356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a453d2c4da9'
down_revision = 'becc8104e8c9'
branch_labels = None
depends_on = None


def upgrade():
    # Cambiar el nombre de la tabla 'disponibilidades' a 'horas'
    op.rename_table('disponibilidades', 'horas')

    # Actualizar la clave foránea en la tabla 'citas' para referirse a 'horas'
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_constraint('citas_fecha_hora_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'horas', ['fecha_hora_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('citas_fecha_hora_id_fkey', 'disponibilidades', ['fecha_hora_id'], ['id'])

    op.create_table('disponibilidades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profesional_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], name='disponibilidades_profesional_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disponibilidades_pkey')
    )
    op.drop_table('horas')
    # ### end Alembic commands ###
